#
# Copyright (c) 2020 INESC TEC <https://www.inesctec.pt>
#
# This Source Code Form is subject to the terms of the European Union
# Public License, v. 1.2. If a copy of the EUPL was not distributed with
# this file, You can obtain one at https://opensource.org/licenses/EUPL-1.2.
#
# SPDX-License-Identifier: EUPL-1.2
#

name: Android Production Staging Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

    paths-ignore:
        - "docs/**"
        - "locales/**"
        - "**/*.md"
        - "LICENSE"

env:
  ANDROID_NDK_VERSION: "21.3.6528147"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: "10"

      - uses: actions/setup-java@v1
        with:
          java-version: "8"
          java-package: "jdk"
          architecture: "x64"

      - name: Get node cache directory path
        id: node-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: node-cache
        name: Cache node dependencies
        with:
          path: ${{ steps.node-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - uses: actions/cache@v2
        id: gradle-cache
        name: Cache gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Install node dependencies
        run: yarn --ignore-scripts --no-audit --prefer-offline --frozen-lockfileyarn --ignore-scripts --frozen-lockfile

      - name: Run unit tests
        run: yarn test:unit

      - name: Run integration tests
        run: yarn test:integration

      - name: Run components tests
        run: yarn test:components

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: "10"

      - uses: actions/setup-java@v1
        with:
          java-version: "8"
          java-package: "jdk"
          architecture: "x64"

      - name: Get node cache directory path
        id: node-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: node-cache
        name: Cache node dependencies
        with:
          path: ${{ steps.node-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - uses: actions/cache@v2
        id: gradle-cache
        name: Cache gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Install node dependencies
        run: yarn --ignore-scripts --no-audit --prefer-offline --frozen-lockfileyarn --ignore-scripts --frozen-lockfile

      - name: Setup environment
        run: |
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${{ env.ANDROID_NDK_VERSION }}"
          wget https://github.com/google/exposure-notifications-android/raw/1803372dd30f151a477f031bd8a25bcf857db8c5/app/libs/play-services-nearby-exposurenotification-1.7.1-eap.aar -P android/app/libs
          echo "${{secrets.ENV_PRODUCTION_STAGING}}" > android/.env

      - name: Build ABB
        run: |
          cd android
          ./gradlew bundleProductionStaging

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleProductionStaging

      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-production-staging.aab
          path: android/app/build/outputs/bundle/productionStaging/app-production-staging.aab

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-production-staging.apk
          path: android/app/build/outputs/apk/production/staging/app-production-staging.apk

      - name: Upload Mapping File
        uses: actions/upload-artifact@v2
        with:
          name: mapping.text
          path: android/app/build/outputs/mapping/productionStaging/mapping.txt

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Download APK artifcat
        uses: actions/download-artifact@v2
        with:
          name: app-production-staging.apk

      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1.3.1
        with:
          appName: ${{secrets.APPCENTER_ORG_ANDROID}}/${{secrets.APPCENTER_APP_PRODUCTION}}
          token: ${{secrets.APPCENTER_TOKEN_ANDROID_PRODUCTION}}
          group: Collaborators
          file: app-production-staging.apk
          notifyTesters: true
          gitReleaseNotes: true
