#
# Copyright (c) 2020 INESC TEC <https://www.inesctec.pt>
#
# This Source Code Form is subject to the terms of the European Union
# Public License, v. 1.2. If a copy of the EUPL was not distributed with
# this file, You can obtain one at https://opensource.org/licenses/EUPL-1.2.
#
# SPDX-License-Identifier: EUPL-1.2
#

name: Android Production Staging Build

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: '10'
      - uses: actions/setup-java@v1
        with:
            java-version: '1.8'
            java-package: jdk
            architecture: x64

      - name: Get node cache directory path
        id: pods-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: node-cache
        name: Cache node dependencies
        with:
          path: ${{ steps.pods-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install node dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: yarn --ignore-scripts

      - name: Setup environment
        run: |
          wget https://github.com/google/exposure-notifications-android/raw/7dc2979051703443895123f83c370f64a81baa38/app/libs/play-services-nearby-18.0.3-eap.aar -P android/app/libs
          echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.3.6528147"
          echo "${{secrets.ENV_PRODUCTION_STAGING}}" > android/.env

      - name: Build ABB
        run: |
          cd android
          ./gradlew bundleProductionStaging \
            -PkeystoreFile="$GITHUB_WORKSPACE/android/app/debug.keystore" \
            -PkeystorePassword="android" \
            -PkeyAlias="androiddebugkey" \
            -PkeyPassword="android"

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleProductionStaging \
            -PkeystoreFile="$GITHUB_WORKSPACE/android/app/debug.keystore" \
            -PkeystorePassword="android" \
            -PkeyAlias="androiddebugkey" \
            -PkeyPassword="android"

      - name: Upload AAB
        uses: actions/upload-artifact@v2
        with:
          name: app-production-staging.aab
          path: android/app/build/outputs/bundle/productionStaging/app-production-staging.aab

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-production-staging.apk
          path: android/app/build/outputs/apk/production/staging/app-production-staging.apk

      - name: Upload Mapping File
        uses: actions/upload-artifact@v2
        with:
          name: mapping.text
          path: android/app/build/outputs/mapping/productionStaging/mapping.txt

  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download APK artifcat
        uses: actions/download-artifact@v2
        with:
          name: app-production-staging.apk

      - name: Upload artifact to App Center
        uses: wzieba/AppCenter-Github-Action@v1.1.1
        with:
          appName: ${{secrets.APPCENTER_ORG}}/${{secrets.APPCENTER_APP_PRODUCTION_STAGING}}
          token: ${{secrets.APPCENTER_TOKEN_PRODUCTION_STAGING}}
          group: Internal
          file: app-production-staging.apk
